### ISSUE TITLE
files not generated

### ISSUE THREAD

**Issue by wedadfcis** [steewsc/template#3]
i installed the plugin and every thing well but the files not generated

**Comment by steewsc** [comment]
Check the logs (Help -> Show Log in ...)
![image](https://user-images.githubusercontent.com/1216079/114431558-eb14cd80-9bbf-11eb-9b69-2b847083d5c4.png)
Open it in Android Studio.

It might be a pretty large file, so you should close Android studio first, then try deleting Log file, open Android Studio again and reproduce the issue, and then open Log file to see what went wrong


It's probably com.intellij.util.IncorrectOperationException: File .... already exists.

**Comment by quannguyen-sre** [comment]
I got the same issue. The error occurs in mviSetupRecipe.kt. projectInstance is null and the project creating process is crash.

**Comment by inkp80** [comment]
I got the same issue too.

```
// Develop Env.
IntelliJ IDEA 2020.3.1 (Community Edition)
Build #IC-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12


// RunIde Env.
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_265-b01 x86_64
VM: OpenJDK 64-Bit Server VM by AdoptOpenJDK
macOS 10.14.5
GC: PS Scavenge, PS MarkSweep
Memory: 455M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.github.steewsc.mvisetup
```

```
public fun com.android.tools.idea.wizard.template.RecipeExecutor.generateManifest(...)
```

```
ERROR - intellij.openapi.progress.Task - java.lang.NoSuchMethodError: com.android.tools.idea.wizard.template.impl.activities.common.CommonRecipesKt.generateManifest$default(Lcom/android/tools/idea/wizard/template/RecipeExecutor;Lcom/android/tools/idea/wizard/template/ModuleTemplateData;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZLcom/android/tools/idea/wizard/template/ThemeData;ZZLjava/io/File;Ljava/io/File;ZILjava/lang/Object;)V 
java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.wizard.template.impl.activities.common.CommonRecipesKt.generateManifest$default(Lcom/android/tools/idea/wizard/template/RecipeExecutor;Lcom/android/tools/idea/wizard/template/ModuleTemplateData;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZLcom/android/tools/idea/wizard/template/ThemeData;ZZLjava/io/File;Ljava/io/File;ZILjava/lang/Object;)V
....

Caused by: java.lang.NoSuchMethodError: com.android.tools.idea.wizard.template.impl.activities.common.CommonRecipesKt.generateManifest$default(Lcom/android/tools/idea/wizard/template/RecipeExecutor;Lcom/android/tools/idea/wizard/template/ModuleTemplateData;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZLcom/android/tools/idea/wizard/template/ThemeData;ZZLjava/io/File;Ljava/io/File;ZILjava/lang/Object;)V
	at other.mviSetup.MviSetupRecipeKt.mviSetup(mviSetupRecipe.kt:36)
	at other.mviSetup.MviSetupTemplateKt$mviSetupTemplate$1$1.invoke(mviSetupTemplate.kt:40)
	at other.mviSetup.MviSetupTemplateKt$mviSetupTemplate$1$1.invoke(mviSetupTemplate.kt)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt$doRender$1.run(NewTemplateRenderer.kt:80)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:107)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:248)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:247)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:305)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:307)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:246)
	at com.intellij.openapi.command.WriteCommandAction.lambda$execute$0(WriteCommandAction.java:231)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:480)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
....

```

and I faced this error too after disable `generateManifest {}`

```
com.intellij.util.IncorrectOperationException: File '/Users/user/AndroidCustomViews/app/src/main/java/com/inkyu/androidcustomviews/FoosActivity.kt' already exists.
	at com.intellij.psi.impl.file.PsiDirectoryImpl.checkAdd(PsiDirectoryImpl.java:458)
	at com.intellij.psi.impl.file.PsiJavaDirectoryImpl.checkAdd(PsiJavaDirectoryImpl.java:80)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.add(PsiDirectoryImpl.java:396)
	at com.intellij.psi.impl.file.PsiJavaDirectoryImpl.add(PsiJavaDirectoryImpl.java:65)
	at other.mviSetup.MviSetupRecipeKt.save(mviSetupRecipe.kt:52)
	at other.mviSetup.MviSetupRecipeKt.mviSetup(mviSetupRecipe.kt:40)
	at other.mviSetup.MviSetupTemplateKt$mviSetupTemplate$1$1.invoke(mviSetupTemplate.kt:40)
	at other.mviSetup.MviSetupTemplateKt$mviSetupTemplate$1$1.invoke(mviSetupTemplate.kt)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt$doRender$1.run(NewTemplateRenderer.kt:80)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:107)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:248)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:247)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:305)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:307)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:246)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:227)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:109)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt.doRender(NewTemplateRenderer.kt:79)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt.render(NewTemplateRenderer.kt:59)
	at com.android.tools.idea.npw.model.NewTemplateRendererKt.render(NewTemplateRenderer.kt:49)
	at com.android.tools.idea.npw.model.RenderTemplateModel$TemplateRenderer.renderTemplate(RenderTemplateModel.kt:190)
	at com.android.tools.idea.npw.model.RenderTemplateModel$TemplateRenderer.render(RenderTemplateModel.kt:159)
	at com.android.tools.idea.npw.model.MultiTemplateRenderer$countDown$2$1$3.run(MultiTemplateRenderer.kt:136)
	at com.intellij.openapi.application.WriteThread.lambda$submit$0(WriteThread.java:27)
	at com.intellij.openapi.application.WriteThread.lambda$submit$1(WriteThread.java:44)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLaterOnWriteThread$11(ApplicationImpl.java:806)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:730)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:1030)
	at com.intellij.openapi.progress.util.ProgressWindow.pumpEventsForHierarchy(ProgressWindow.java:199)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$3(ProgressWindow.java:189)
	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:857)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:188)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$legacyExec$6(ProgressRunner.java:302)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683)
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010)
	at com.intellij.openapi.progress.impl.ProgressRunner.legacyExec(ProgressRunner.java:300)
	at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:169)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runSynchronously(CoreProgressManager.java:345)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:330)
	at com.intellij.openapi.progress.Task.queue(Task.java:109)
	at com.android.tools.idea.npw.model.ExistingProjectModelData$multiTemplateRenderer$1.invoke(NewAndroidModuleModel.kt:68)
	at com.android.tools.idea.npw.model.ExistingProjectModelData$multiTemplateRenderer$1.invoke(NewAndroidModuleModel.kt:50)
	at com.android.tools.idea.npw.model.MultiTemplateRenderer.countDown(MultiTemplateRenderer.kt:123)
	at com.android.tools.idea.npw.model.MultiTemplateRenderer.requestRender(MultiTemplateRenderer.kt:102)
	at com.android.tools.idea.npw.model.RenderTemplateModel.handleFinished(RenderTemplateModel.kt:101)
	at com.android.tools.idea.wizard.model.ModelWizard.handleFinished(ModelWizard.java:402)
	at com.android.tools.idea.wizard.model.ModelWizard.goForward(ModelWizard.java:330)
	at com.android.tools.idea.wizard.model.ModelWizardDialog$FinishAction.doAction(ModelWizardDialog.java:313)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1819)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
        ...
```

**Comment by BurningDroid** [comment]
> I got the same issue too.
> 
> ```
> // Develop Env.
> IntelliJ IDEA 2020.3.1 (Community Edition)
> Build #IC-203.6682.168, built on December 29, 2020
> Runtime version: 11.0.9.1+11-b1145.63 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 10.14.5
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1979M
> Cores: 12
> 
> 
> // RunIde Env.
> Android Studio 4.1.2
> Build #AI-201.8743.12.41.7042882, built on December 20, 2020
> Runtime version: 1.8.0_265-b01 x86_64
> VM: OpenJDK 64-Bit Server VM by AdoptOpenJDK
> macOS 10.14.5
> GC: PS Scavenge, PS MarkSweep
> Memory: 455M
> Cores: 12
> Registry: external.system.auto.import.disabled=true
> Non-Bundled Plugins: com.github.steewsc.mvisetup
> ```
> 
> ```
> public fun com.android.tools.idea.wizard.template.RecipeExecutor.generateManifest(...)
> ```
> 
> ```
> ERROR - intellij.openapi.progress.Task - java.lang.NoSuchMethodError: com.android.tools.idea.wizard.template.impl.activities.common.CommonRecipesKt.generateManifest$default(Lcom/android/tools/idea/wizard/template/RecipeExecutor;Lcom/android/tools/idea/wizard/template/ModuleTemplateData;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZLcom/android/tools/idea/wizard/template/ThemeData;ZZLjava/io/File;Ljava/io/File;ZILjava/lang/Object;)V 
> java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.wizard.template.impl.activities.common.CommonRecipesKt.generateManifest$default(Lcom/android/tools/idea/wizard/template/RecipeExecutor;Lcom/android/tools/idea/wizard/template/ModuleTemplateData;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZLcom/android/tools/idea/wizard/template/ThemeData;ZZLjava/io/File;Ljava/io/File;ZILjava/lang/Object;)V
> ....
> 
> Caused by: java.lang.NoSuchMethodError: com.android.tools.idea.wizard.template.impl.activities.common.CommonRecipesKt.generateManifest$default(Lcom/android/tools/idea/wizard/template/RecipeExecutor;Lcom/android/tools/idea/wizard/template/ModuleTemplateData;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZLcom/android/tools/idea/wizard/template/ThemeData;ZZLjava/io/File;Ljava/io/File;ZILjava/lang/Object;)V
> 	at other.mviSetup.MviSetupRecipeKt.mviSetup(mviSetupRecipe.kt:36)
> 	at other.mviSetup.MviSetupTemplateKt$mviSetupTemplate$1$1.invoke(mviSetupTemplate.kt:40)
> 	at other.mviSetup.MviSetupTemplateKt$mviSetupTemplate$1$1.invoke(mviSetupTemplate.kt)
> 	at com.android.tools.idea.npw.model.NewTemplateRendererKt$doRender$1.run(NewTemplateRenderer.kt:80)
> 	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:107)
> 	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
> 	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:248)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
> 	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:247)
> 	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:305)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
> 	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:307)
> 	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:246)
> 	at com.intellij.openapi.command.WriteCommandAction.lambda$execute$0(WriteCommandAction.java:231)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:480)
> 	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:124)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
> 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> ....
> ```
> 
> and I faced this error too after disable `generateManifest {}`
> 
> ```
> com.intellij.util.IncorrectOperationException: File '/Users/user/AndroidCustomViews/app/src/main/java/com/inkyu/androidcustomviews/FoosActivity.kt' already exists.
> 	at com.intellij.psi.impl.file.PsiDirectoryImpl.checkAdd(PsiDirectoryImpl.java:458)
> 	at com.intellij.psi.impl.file.PsiJavaDirectoryImpl.checkAdd(PsiJavaDirectoryImpl.java:80)
> 	at com.intellij.psi.impl.file.PsiDirectoryImpl.add(PsiDirectoryImpl.java:396)
> 	at com.intellij.psi.impl.file.PsiJavaDirectoryImpl.add(PsiJavaDirectoryImpl.java:65)
> 	at other.mviSetup.MviSetupRecipeKt.save(mviSetupRecipe.kt:52)
> 	at other.mviSetup.MviSetupRecipeKt.mviSetup(mviSetupRecipe.kt:40)
> 	at other.mviSetup.MviSetupTemplateKt$mviSetupTemplate$1$1.invoke(mviSetupTemplate.kt:40)
> 	at other.mviSetup.MviSetupTemplateKt$mviSetupTemplate$1$1.invoke(mviSetupTemplate.kt)
> 	at com.android.tools.idea.npw.model.NewTemplateRendererKt$doRender$1.run(NewTemplateRenderer.kt:80)
> 	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:107)
> 	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
> 	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:248)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
> 	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:247)
> 	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:305)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
> 	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:307)
> 	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:246)
> 	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:227)
> 	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:109)
> 	at com.android.tools.idea.npw.model.NewTemplateRendererKt.doRender(NewTemplateRenderer.kt:79)
> 	at com.android.tools.idea.npw.model.NewTemplateRendererKt.render(NewTemplateRenderer.kt:59)
> 	at com.android.tools.idea.npw.model.NewTemplateRendererKt.render(NewTemplateRenderer.kt:49)
> 	at com.android.tools.idea.npw.model.RenderTemplateModel$TemplateRenderer.renderTemplate(RenderTemplateModel.kt:190)
> 	at com.android.tools.idea.npw.model.RenderTemplateModel$TemplateRenderer.render(RenderTemplateModel.kt:159)
> 	at com.android.tools.idea.npw.model.MultiTemplateRenderer$countDown$2$1$3.run(MultiTemplateRenderer.kt:136)
> 	at com.intellij.openapi.application.WriteThread.lambda$submit$0(WriteThread.java:27)
> 	at com.intellij.openapi.application.WriteThread.lambda$submit$1(WriteThread.java:44)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLaterOnWriteThread$11(ApplicationImpl.java:806)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
> 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
> 	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:730)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
> 	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:1030)
> 	at com.intellij.openapi.progress.util.ProgressWindow.pumpEventsForHierarchy(ProgressWindow.java:199)
> 	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$3(ProgressWindow.java:189)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:857)
> 	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:188)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$legacyExec$6(ProgressRunner.java:302)
> 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
> 	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683)
> 	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.legacyExec(ProgressRunner.java:300)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:248)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:169)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:426)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:494)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:84)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runSynchronously(CoreProgressManager.java:345)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:330)
> 	at com.intellij.openapi.progress.Task.queue(Task.java:109)
> 	at com.android.tools.idea.npw.model.ExistingProjectModelData$multiTemplateRenderer$1.invoke(NewAndroidModuleModel.kt:68)
> 	at com.android.tools.idea.npw.model.ExistingProjectModelData$multiTemplateRenderer$1.invoke(NewAndroidModuleModel.kt:50)
> 	at com.android.tools.idea.npw.model.MultiTemplateRenderer.countDown(MultiTemplateRenderer.kt:123)
> 	at com.android.tools.idea.npw.model.MultiTemplateRenderer.requestRender(MultiTemplateRenderer.kt:102)
> 	at com.android.tools.idea.npw.model.RenderTemplateModel.handleFinished(RenderTemplateModel.kt:101)
> 	at com.android.tools.idea.wizard.model.ModelWizard.handleFinished(ModelWizard.java:402)
> 	at com.android.tools.idea.wizard.model.ModelWizard.goForward(ModelWizard.java:330)
> 	at com.android.tools.idea.wizard.model.ModelWizardDialog$FinishAction.doAction(ModelWizardDialog.java:313)
> 	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1819)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> 	at java.awt.Component.processMouseEvent(Component.java:6539)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6304)
> 	at java.awt.Container.processEvent(Container.java:2239)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2297)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
>         ...
> ```

I have the same issue.
Did you solve this issue?? (한국분 같으신데.. 혹시 해결하셨을까요?)

**Comment by stevicat** [comment]
I've just pushed an update where it doesn't use project instance hack.
Checkout and update **androidStudioPath** or **androidStudioPathMacOS**  in **gradle.properties** to point to your Android Studio installation:
![image](https://user-images.githubusercontent.com/85672820/128576160-11aadb56-4632-45ff-9cb1-abc752dc5896.png)


Also, you'll find three run configurations:
![image](https://user-images.githubusercontent.com/85672820/128575976-a4b623dd-0634-47dc-8538-6ba1b902cf75.png)
you can use **template-example [runIde]** to easily build&run your plugin in AS without messing your working AS and also see a live logs from it.

**Comment by steewsc** [comment]
I've just pushed an update where it doesn't use project instance hack.
Checkout and update **androidStudioPath** or **androidStudioPathMacOS**  in **gradle.properties** to point to your Android Studio installation:
![image](https://user-images.githubusercontent.com/85672820/128576160-11aadb56-4632-45ff-9cb1-abc752dc5896.png)


Also, you'll find three run configurations:
![image](https://user-images.githubusercontent.com/85672820/128575976-a4b623dd-0634-47dc-8538-6ba1b902cf75.png)
you can use **template-example [runIde]** to easily build&run your plugin in AS without messing your working AS and also see a live logs from it.
